version: "3.8"

services:
  sablon:
    build:
      context: .
      dockerfile: Dockerfile
    image: 4teamwork/sablon:latest
    ports:
      - 3000:8080
    environment:
      - SABLON_CALL_TIMEOUT=5
